parameters:
    rjm_maxmind.geolocation.country.class: RJM\Bundle\MaxmindBundle\Geolocation\CountryGeolocation

services:
    rjm_maxmind.geolocation.country:
        scope: request
        class: %rjm_maxmind.geolocation.country.class%
        arguments: [@request, %rjm_maxmind.service_url%, %rjm_maxmind.licence_key%]
